include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/gen/**
  errors:
    todo: error
    unused_import: error
    unused_local_variable: error
    dead_code: error

linter:
  rules:
    avoid_print: true
