name: CI

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

# Ensure this permission exists at the workflow level (or repository default)
permissions:
  contents: write   # required to create releases

env:
  PROJECT_DIR: paisasplit  # <--- change if your app dir differs

jobs:
  build-android:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Flutter setup
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      # 👇 NEW: regenerate/upgrade Android Gradle project for current Flutter
      - name: Ensure Android scaffolding is up-to-date
        run: flutter create . --platforms=android

      - name: Pub get
        run: flutter pub get

      - name: Codegen
        run: dart run build_runner build -d

      - name: Analyze (treat warnings as errors)
        run: dart analyze --fatal-infos --fatal-warnings

      - name: Tests
        run: flutter test

      # Build APKs in CI (you asked to keep this)
      - name: Build DEBUG APK (universal)
        run: flutter build apk --debug

      - name: Build RELEASE APKs (per-ABI, unsigned)
        run: flutter build apk --release --split-per-abi

      - name: Collect artifacts
        run: |
          mkdir -p artifacts
          cp build/app/outputs/flutter-apk/app-debug.apk artifacts/PaisaSplit-debug-universal.apk
          cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk artifacts/PaisaSplit-release-arm64-v8a-UNSIGNED.apk || true
          cp build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk artifacts/PaisaSplit-release-armeabi-v7a-UNSIGNED.apk || true
          cp build/app/outputs/flutter-apk/app-x86_64-release.apk artifacts/PaisaSplit-release-x86_64-UNSIGNED.apk || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PaisaSplit-APK-${{ github.sha }}
          path: ${{ env.PROJECT_DIR }}/artifacts/*
          retention-days: 14
  # Add this as a NEW job in the same workflow file, below build-android
  release-apk:
    # Only run on tag pushes
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (for changelog/notes if needed)
        uses: actions/checkout@v4

      - name: Download build artifacts from previous job
        uses: actions/download-artifact@v4
        with:
          name: PaisaSplit-APK-${{ github.sha }}
          path: release-apks

      # Create or update a GitHub Release for this tag and upload APKs
      - name: Create GitHub Release and upload APKs
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: PaisaSplit ${{ github.ref_name }}
          body: |
            APKs for ${{ github.ref_name }}.
            - Debug (universal) for quick testing
            - Unsigned per-ABI release builds for distribution/signing
          draft: false
          prerelease: false
          files: |
            release-apks/PaisaSplit-debug-universal.apk
            release-apks/PaisaSplit-release-arm64-v8a-UNSIGNED.apk
            release-apks/PaisaSplit-release-armeabi-v7a-UNSIGNED.apk
            release-apks/PaisaSplit-release-x86_64-UNSIGNED.apk

        


      # Optional: Enable this section when signing release builds for tagged versions.
      # - name: Build signed release APKs
      #   if: startsWith(github.ref, 'refs/tags/')
      #   env:
      #     ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      #     ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      #     ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      #     ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      #   run: |
      #     echo "${ANDROID_KEYSTORE_BASE64}" | base64 --decode > android/app/release.keystore
      #     flutter build apk --release --split-per-abi --obfuscate --split-debug-info=build/debug-info
      #     rm -f android/app/release.keystore
