name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

# needed for creating Releases
permissions:
  contents: write

env:
  PROJECT_DIR: paisasplit  # <<--- CHANGE if your app folder name differs

jobs:
  build-android:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Flutter setup
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      # Keeps Android/Gradle scaffolding compatible with the runner's Flutter
      - name: Ensure Android scaffolding is up-to-date
        run: flutter create . --platforms=android

      - name: Pub get
        run: flutter pub get

      - name: Codegen
        run: dart run build_runner build -d

      - name: Analyze (warnings = errors)
        run: dart analyze --fatal-infos --fatal-warnings

      - name: Tests
        run: flutter test

      # ---- BUILD DEBUG APK ONLY ----
      - name: Build DEBUG APK (universal)
        run: flutter build apk --debug

      # Optional: keep artifact for PR view
      - name: Upload artifact (debug APK)
        uses: actions/upload-artifact@v4
        with:
          name: PaisaSplit-debug-${{ github.sha }}
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 7

      # ---- FAST DOWNLOADS: publish debug APK to a Release per run ----
      # Note: GitHub will also show the auto "Source code" zips; that's normal.
      - name: Create GitHub Release for this run (attach debug APK)
        if: ${{ success() && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ci-${{ github.run_id }}                      # auto tag (no manual push)
          name: PaisaSplit CI Build ${{ github.run_number }}     # human title
          body: |
            Debug APK for run ${{ github.run_id }} on `${{ github.ref_name }}`.
            Install on device for quick testing.
          draft: false
          prerelease: true
          files: |
            ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-debug.apk
        


      # Optional: Enable this section when signing release builds for tagged versions.
      # - name: Build signed release APKs
      #   if: startsWith(github.ref, 'refs/tags/')
      #   env:
      #     ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      #     ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      #     ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      #     ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      #   run: |
      #     echo "${ANDROID_KEYSTORE_BASE64}" | base64 --decode > android/app/release.keystore
      #     flutter build apk --release --split-per-abi --obfuscate --split-debug-info=build/debug-info
      #     rm -f android/app/release.keystore
